// Created by rolf on 24-04-20.
//

#ifndef SOCCER_SRC_COMMON_MATH_GEOMETRY_LINEBASE_H_
#define SOCCER_SRC_COMMON_MATH_GEOMETRY_LINEBASE_H_

class LineBase {

};

#endif //SOCCER_SRC_COMMON_MATH_GEOMETRY_LINEBASE_H_
