language: cpp
compiler:
  - gcc
notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required

addons:
  apt:
    packages:
      - cmake
      - libprotobuf-dev
      - libbenchmark-dev
      - libeigen3-dev
      - protobuf-compiler
      - lcov
      - qt5-default
install:
  - cd ~/
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - mkdir install
  - cd install
  - cmake ../
  - make
  - sudo make install

script:
  - cd $TRAVIS_BUILD_DIR
  - ./runCoverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -f build/total.info || echo "Codecov did not collect coverage reports"


