//
// Created by rolf on 09-05-20.
//

#ifndef SOCCER_SRC_FRAMEWORK_AUTOREFEREE_EVENTDETECTION_EVENTDETECTOR_H_
#define SOCCER_SRC_FRAMEWORK_AUTOREFEREE_EVENTDETECTION_EVENTDETECTOR_H_

class EventDetector {
  virtual bool turnedOnInGameState() const = 0;
};

#endif //SOCCER_SRC_FRAMEWORK_AUTOREFEREE_EVENTDETECTION_EVENTDETECTOR_H_
