//
// Created by rolf on 29-07-20.
//

#ifndef SOCCER_INREASINGDISTANCEDETECTOR_H
#define SOCCER_INREASINGDISTANCEDETECTOR_H


class InreasingDistanceDetector {

};


#endif //SOCCER_INREASINGDISTANCEDETECTOR_H
