//
// Created by rolf on 21-12-20.
//

#ifndef SOCCER_SRC_FRAMEWORK_VISIONFILTER_BALL_CAMERABALLFILTER_H_
#define SOCCER_SRC_FRAMEWORK_VISIONFILTER_BALL_CAMERABALLFILTER_H_

class CameraBallFilter {

};

#endif //SOCCER_SRC_FRAMEWORK_VISIONFILTER_BALL_CAMERABALLFILTER_H_
