//
// Created by rolf on 05-01-21.
//

#ifndef SOCCER_SRC_FRAMEWORK_VISIONFILTER_INCLUDE_VISIONFILTER_BALL_KICK_ESTIMATION_GROUND_GROUNDFITTER_H_
#define SOCCER_SRC_FRAMEWORK_VISIONFILTER_INCLUDE_VISIONFILTER_BALL_KICK_ESTIMATION_GROUND_GROUNDFITTER_H_

class GroundFitter {

};

#endif //SOCCER_SRC_FRAMEWORK_VISIONFILTER_INCLUDE_VISIONFILTER_BALL_KICK_ESTIMATION_GROUND_GROUNDFITTER_H_
